services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gig-galaxy-backend
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - API_BASE_PATH=/api
    networks:
      - gig-galaxy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gig-galaxy-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.quasar
    ports:
      - "9000:9000"
    environment:
      - DOCKER_ENV=true
      - VITE_API_BASE_URL=/api
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - gig-galaxy-network

networks:
  gig-galaxy-network:
    driver: bridge
